
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.jprs.jp/jp/property_updates_on_error_out-of-range
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisJprsJpJpPropertyUpdatesOnErrorOutOfRange(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.jprs.jp/jp/property_updates_on_error_out-of-range.txt"
        host         = "whois.jprs.jp"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2010-10-18 11:30:47 JST'))
