
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.nic.tv/tv/property_nameserver_no_nameserver
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNicTvTvPropertyNameserverNoNameserver(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.nic.tv/tv/property_nameserver_no_nameserver.txt"
        host         = "whois.nic.tv"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(self.record.nameservers, [])
