
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.ua/ua/uanic/property_contacts_multiple
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisUaUaUanicPropertyContactsMultiple(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.ua/ua/uanic/property_contacts_multiple.txt"
        host         = "whois.ua"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 2)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "KG780-UANIC")
        eq_(self.record.technical_contacts[0].name, None)
        eq_(self.record.technical_contacts[0].organization, "Kyivstar GSM")
        eq_(self.record.technical_contacts[0].address, "Chervonozoryanyi Av., 51")
        eq_(self.record.technical_contacts[0].city, "KYIV")
        eq_(self.record.technical_contacts[0].zip, "03110")
        eq_(self.record.technical_contacts[0].state, None)
        eq_(self.record.technical_contacts[0].country, "UA")
        eq_(self.record.technical_contacts[0].country_code, None)
        eq_(self.record.technical_contacts[0].phone, "+380 (67) 2372213")
        eq_(self.record.technical_contacts[0].fax, "+380 (44) 2473954")
        eq_(self.record.technical_contacts[0].email, "dnsmaster@kyivstar.net")
        eq_(self.record.technical_contacts[0].created_on, None)
        eq_(self.record.technical_contacts[0].updated_on, time_parse('2008-09-02 12:52:47'))
        eq_(self.record.technical_contacts[1].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[1].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[1].id, "EIC-UANIC")
        eq_(self.record.technical_contacts[1].name, None)
        eq_(self.record.technical_contacts[1].organization, "\"ElVisti Information Center\", LLC\nООО \"Информационный центр \"Электронные вести\"\nТОВ \"ІЦ ЕЛВІСТІ\"")
        eq_(self.record.technical_contacts[1].address, "а/с, 151")
        eq_(self.record.technical_contacts[1].city, "КИЇВ")
        eq_(self.record.technical_contacts[1].zip, "03037")
        eq_(self.record.technical_contacts[1].state, None)
        eq_(self.record.technical_contacts[1].country, "UA")
        eq_(self.record.technical_contacts[1].country_code, None)
        eq_(self.record.technical_contacts[1].phone, "+38044 239-90-91")
        eq_(self.record.technical_contacts[1].fax, None)
        eq_(self.record.technical_contacts[1].email, "hostmaster@visti.net")
        eq_(self.record.technical_contacts[1].created_on, None)
        eq_(self.record.technical_contacts[1].updated_on, time_parse('2011-12-15 11:33:14'))
