
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.verisign-grs.com/com/property_registrar_with_multiple_entries
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisVerisignGrsComComPropertyRegistrarWithMultipleEntries(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.verisign-grs.com/com/property_registrar_with_multiple_entries.txt"
        host         = "whois.verisign-grs.com"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, None)
        eq_(self.record.registrar.name, "MARKMONITOR INC.")
        eq_(self.record.registrar.organization, None)
        eq_(self.record.registrar.url, "http://www.markmonitor.com")
