
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.educause.edu/property_contacts_case4
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisEducauseEduPropertyContactsCase4(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.educause.edu/property_contacts_case4.txt"
        host         = "whois.educause.edu"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].id, None)
        eq_(self.record.admin_contacts[0].name, "ITS Business Office\nSyracuse University\nInformation Technology and Services\nCenter for Science and Technology")
        eq_(self.record.admin_contacts[0].organization, None)
        eq_(self.record.admin_contacts[0].address, None)
        eq_(self.record.admin_contacts[0].city, "Syracuse")
        eq_(self.record.admin_contacts[0].zip, "13244")
        eq_(self.record.admin_contacts[0].state, "NY")
        eq_(self.record.admin_contacts[0].country, "UNITED STATES")
        eq_(self.record.admin_contacts[0].country_code, None)
        eq_(self.record.admin_contacts[0].phone, "(315) 443-6189")
        eq_(self.record.admin_contacts[0].fax, None)
        eq_(self.record.admin_contacts[0].email, "itsoffice@syr.edu")
