
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.networksolutions.com/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNetworksolutionsComStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.networksolutions.com/status_registered.txt"
        host         = "whois.networksolutions.com"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, 'registered')

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "xif.com")

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 3)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "ns01.xif.com")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "ns-east.cerf.net")
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "ns-west.cerf.net")

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, None)
        eq_(self.record.admin_contacts[0].name, "Communications, XIF ContactMiddleName")
        eq_(self.record.admin_contacts[0].organization, "XIF Communications")
        eq_(self.record.admin_contacts[0].address, "1200 New Hampshire Avenue NW")
        eq_(self.record.admin_contacts[0].city, "Washington")
        eq_(self.record.admin_contacts[0].zip, "20036")
        eq_(self.record.admin_contacts[0].state, "DC")
        eq_(self.record.admin_contacts[0].country, None)
        eq_(self.record.admin_contacts[0].country_code, "US")
        eq_(self.record.admin_contacts[0].phone, "202-463-7200")
        eq_(self.record.admin_contacts[0].fax, "202-318-4003")
        eq_(self.record.admin_contacts[0].email, "noc@xif.com")
        eq_(self.record.admin_contacts[0].created_on, None)
        eq_(self.record.admin_contacts[0].updated_on, None)

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('1997-06-10'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, "2")
        eq_(self.record.registrar.name, "NETWORK SOLUTIONS, LLC.")
        eq_(self.record.registrar.organization, "NETWORK SOLUTIONS, LLC.")
        eq_(self.record.registrar.url, "http//www.networksolutions.com/en_US/")

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, None)
        eq_(self.record.registrant_contacts[0].name, "XIF Communications")
        eq_(self.record.registrant_contacts[0].organization, "XIF Communications")
        eq_(self.record.registrant_contacts[0].address, "1200 New Hampshire Avenue NW")
        eq_(self.record.registrant_contacts[0].city, "Washington")
        eq_(self.record.registrant_contacts[0].zip, "20036")
        eq_(self.record.registrant_contacts[0].state, "DC")
        eq_(self.record.registrant_contacts[0].country, None)
        eq_(self.record.registrant_contacts[0].country_code, "US")
        eq_(self.record.registrant_contacts[0].phone, "202-463-7200")
        eq_(self.record.registrant_contacts[0].fax, "999-999-9999")
        eq_(self.record.registrant_contacts[0].email, "noc@xif.com")
        eq_(self.record.registrant_contacts[0].created_on, None)
        eq_(self.record.registrant_contacts[0].updated_on, None)

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, None)
        eq_(self.record.technical_contacts[0].name, "Communications, XIF ContactMiddleName")
        eq_(self.record.technical_contacts[0].organization, "XIF Communications")
        eq_(self.record.technical_contacts[0].address, "1200 New Hampshire Avenue NW")
        eq_(self.record.technical_contacts[0].city, "Washington")
        eq_(self.record.technical_contacts[0].zip, "20036")
        eq_(self.record.technical_contacts[0].state, "DC")
        eq_(self.record.technical_contacts[0].country, None)
        eq_(self.record.technical_contacts[0].country_code, "US")
        eq_(self.record.technical_contacts[0].phone, "202-463-7200")
        eq_(self.record.technical_contacts[0].fax, "202-318-4003")
        eq_(self.record.technical_contacts[0].email, "noc@xif.com")
        eq_(self.record.technical_contacts[0].created_on, None)
        eq_(self.record.technical_contacts[0].updated_on, None)

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2012-02-13'))

    def test_domain_id(self):
        eq_(self.record.domain_id, "")

    def test_expires_on(self):
        eq_(self.record.expires_on.__class__.__name__, 'datetime')
        eq_(self.record.expires_on, time_parse('2014-06-09'))
