
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.eu/property_nameservers
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisEuPropertyNameservers(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.eu/property_nameservers.txt"
        host         = "whois.eu"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 5)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "a.nic.eu")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "l.nic.eu")
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "p.nic.eu")
        eq_(self.record.nameservers[3].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[3].name, "ns1.eurid.eu")
        eq_(self.record.nameservers[3].ipv4, "91.220.191.220")
        eq_(self.record.nameservers[3].ipv6, None)
        eq_(self.record.nameservers[4].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[4].name, "ns2.eurid.eu")
        eq_(self.record.nameservers[4].ipv4, "195.234.53.220")
        eq_(self.record.nameservers[4].ipv6, None)
