
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.ati.tn/property_contact_updated_none
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisAtiTnPropertyContactUpdatedNone(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.ati.tn/property_contact_updated_none.txt"
        host         = "whois.ati.tn"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].name, "MAISON DE BIEN HOTELIERS ET EQ Farhat Riadh")
        eq_(self.record.registrant_contacts[0].created_on, time_parse('2013-12-13 20:00:57'))
        eq_(self.record.registrant_contacts[0].updated_on, None)
