
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.dns.pl/property_expires_on_not_defined
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisDnsPlPropertyExpiresOnNotDefined(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.dns.pl/property_expires_on_not_defined.txt"
        host         = "whois.dns.pl"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_expires_on(self):
        eq_(self.record.expires_on, None)
