
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.nic.uk/status_invalid
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNicUkStatusInvalid(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.nic.uk/status_invalid.txt"
        host         = "whois.nic.uk"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, 'invalid')

    def test_valid(self):
        eq_(self.record.valid, False)

    def test_invalid(self):
        eq_(self.record.invalid, True)
