
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.gandi.net/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisGandiNetStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.gandi.net/status_registered.txt"
        host         = "whois.gandi.net"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, 'registered')

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "gandi.net")

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 4)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "dns0.gandi.net")
        eq_(self.record.nameservers[0].ipv4, None)
        eq_(self.record.nameservers[0].ipv6, None)
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "dns1.gandi.net")
        eq_(self.record.nameservers[1].ipv4, None)
        eq_(self.record.nameservers[1].ipv6, None)
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "dns2.gandi.net")
        eq_(self.record.nameservers[2].ipv4, None)
        eq_(self.record.nameservers[2].ipv6, None)
        eq_(self.record.nameservers[3].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[3].name, "dns3.gandi.net")
        eq_(self.record.nameservers[3].ipv4, None)
        eq_(self.record.nameservers[3].ipv6, None)

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, None)
        eq_(self.record.admin_contacts[0].name, "Noc GANDI")
        eq_(self.record.admin_contacts[0].organization, "GANDI SAS")
        eq_(self.record.admin_contacts[0].address, "63-65 Boulevard MASSENA")
        eq_(self.record.admin_contacts[0].city, "Paris")
        eq_(self.record.admin_contacts[0].zip, "75013")
        eq_(self.record.admin_contacts[0].country, None)
        eq_(self.record.admin_contacts[0].country_code, "FR")
        eq_(self.record.admin_contacts[0].phone, "+33.143737851")
        eq_(self.record.admin_contacts[0].fax, "+33.143731851")
        eq_(self.record.admin_contacts[0].email, "12e7da77f638acdf8d9f4d0b828ca80c-248842@contact.gandi.net")
        eq_(self.record.admin_contacts[0].created_on, None)
        eq_(self.record.admin_contacts[0].updated_on, None)

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('2000-02-23 12:12:59 UTC'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, "81")
        eq_(self.record.registrar.name, "GANDI SAS")
        eq_(self.record.registrar.organization, "GANDI SAS")
        eq_(self.record.registrar.url, "http://www.gandi.net")

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, None)
        eq_(self.record.registrant_contacts[0].name, "Stephan RAMOIN")
        eq_(self.record.registrant_contacts[0].organization, "Gandi SAS")
        eq_(self.record.registrant_contacts[0].address, "63-65 Boulevard Massena")
        eq_(self.record.registrant_contacts[0].city, "Paris")
        eq_(self.record.registrant_contacts[0].zip, "75013")
        eq_(self.record.registrant_contacts[0].country, None)
        eq_(self.record.registrant_contacts[0].country_code, "FR")
        eq_(self.record.registrant_contacts[0].phone, "+33.143737851")
        eq_(self.record.registrant_contacts[0].fax, "+33.143731851")
        eq_(self.record.registrant_contacts[0].email, "61ebd5b3df9f45f2b3f67f6dd01e1049-523678@contact.gandi.net")
        eq_(self.record.registrant_contacts[0].created_on, None)
        eq_(self.record.registrant_contacts[0].updated_on, None)

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, None)
        eq_(self.record.technical_contacts[0].name, "Noc GANDI")
        eq_(self.record.technical_contacts[0].organization, "GANDI SAS")
        eq_(self.record.technical_contacts[0].address, "63-65 Boulevard MASSENA")
        eq_(self.record.technical_contacts[0].city, "Paris")
        eq_(self.record.technical_contacts[0].zip, "75013")
        eq_(self.record.technical_contacts[0].country, None)
        eq_(self.record.technical_contacts[0].country_code, "FR")
        eq_(self.record.technical_contacts[0].phone, "+33.143737851")
        eq_(self.record.technical_contacts[0].fax, "+33.143731851")
        eq_(self.record.technical_contacts[0].email, "12e7da77f638acdf8d9f4d0b828ca80c-248842@contact.gandi.net")
        eq_(self.record.technical_contacts[0].created_on, None)
        eq_(self.record.technical_contacts[0].updated_on, None)

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2013-10-23 18:42:52 UTC'))

    def test_domain_id(self):
        eq_(self.record.domain_id, "6683836_DOMAIN_NET-VRSN")

    def test_expires_on(self):
        eq_(self.record.expires_on.__class__.__name__, 'datetime')
        eq_(self.record.expires_on, time_parse('2023-05-21 14:09:56 UTC'))
