
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.dot.cf/property_expires_on_blank
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisDotCfPropertyExpiresOnBlank(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.dot.cf/property_expires_on_blank.txt"
        host         = "whois.dot.cf"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_expires_on(self):
        eq_(self.record.expires_on, None)
