
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.nic.it/property_contact_with_company_in_address
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNicItPropertyContactWithCompanyInAddress(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.nic.it/property_contact_with_company_in_address.txt"
        host         = "whois.nic.it"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "AARS1-ITNIC")
        eq_(self.record.technical_contacts[0].name, "Andrea Antonio Renato Stratta")
        eq_(self.record.technical_contacts[0].organization, "UCI Italia Srl")
        eq_(self.record.technical_contacts[0].address, "Via E. Fermi, 161")
        eq_(self.record.technical_contacts[0].city, "Roma")
        eq_(self.record.technical_contacts[0].zip, "00146")
        eq_(self.record.technical_contacts[0].state, "RM")
        eq_(self.record.technical_contacts[0].country_code, "IT")
        eq_(self.record.technical_contacts[0].created_on, time_parse('2006-08-16 00:00:00'))
        eq_(self.record.technical_contacts[0].updated_on, time_parse('2007-03-01 07:48:42'))
