
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.educause.edu/property_contact_registrant_with_additional_organization
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisEducauseEduPropertyContactRegistrantWithAdditionalOrganization(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.educause.edu/property_contact_registrant_with_additional_organization.txt"
        host         = "whois.educause.edu"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, None)
        eq_(self.record.registrant_contacts[0].name, None)
        eq_(self.record.registrant_contacts[0].organization, "Harvard University")
        eq_(self.record.registrant_contacts[0].address, "HUIT Network Services\n60 Oxford Street")
        eq_(self.record.registrant_contacts[0].city, "Cambridge")
        eq_(self.record.registrant_contacts[0].zip, "02138")
        eq_(self.record.registrant_contacts[0].state, "MA")
        eq_(self.record.registrant_contacts[0].country, "UNITED STATES")
        eq_(self.record.registrant_contacts[0].country_code, None)
        eq_(self.record.registrant_contacts[0].phone, None)
        eq_(self.record.registrant_contacts[0].fax, None)
        eq_(self.record.registrant_contacts[0].email, None)
