
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.rrpproxy.net/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisRrpproxyNetStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.rrpproxy.net/status_registered.txt"
        host         = "whois.rrpproxy.net"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, 'registered')

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "multisafepay.com")

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 2)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "ns.teletik.nl")
        eq_(self.record.nameservers[0].ipv4, None)
        eq_(self.record.nameservers[0].ipv6, None)
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "ns3.teletik.nl")
        eq_(self.record.nameservers[1].ipv4, None)
        eq_(self.record.nameservers[1].ipv6, None)

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, "P-OEG220")
        eq_(self.record.admin_contacts[0].name, "Olaf Geurs")
        eq_(self.record.admin_contacts[0].organization, "ION")
        eq_(self.record.admin_contacts[0].address, "Vlierweg 12")
        eq_(self.record.admin_contacts[0].city, "Amsterdam")
        eq_(self.record.admin_contacts[0].zip, "1032 LG")
        eq_(self.record.admin_contacts[0].state, "NH")
        eq_(self.record.admin_contacts[0].country, None)
        eq_(self.record.admin_contacts[0].country_code, "NL")
        eq_(self.record.admin_contacts[0].phone, "+31.204949100")
        eq_(self.record.admin_contacts[0].fax, None)
        eq_(self.record.admin_contacts[0].email, "domains@reasonnet.com")
        eq_(self.record.admin_contacts[0].created_on, None)
        eq_(self.record.admin_contacts[0].updated_on, None)

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('2006-02-03 19:44:56 UTC'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, "269")
        eq_(self.record.registrar.name, "Key-Systems GmbH")
        eq_(self.record.registrar.organization, "Key-Systems GmbH")
        eq_(self.record.registrar.url, "http://www.reasonnet.com")

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, "P-DQJ547")
        eq_(self.record.registrant_contacts[0].name, "David Jacobs")
        eq_(self.record.registrant_contacts[0].organization, "ReasonNet B.V.")
        eq_(self.record.registrant_contacts[0].address, "Gyroscoopweg 134")
        eq_(self.record.registrant_contacts[0].city, "Amsterdam")
        eq_(self.record.registrant_contacts[0].zip, "1042 AZ")
        eq_(self.record.registrant_contacts[0].state, "NH")
        eq_(self.record.registrant_contacts[0].country, None)
        eq_(self.record.registrant_contacts[0].country_code, "NL")
        eq_(self.record.registrant_contacts[0].phone, "+31.205060035")
        eq_(self.record.registrant_contacts[0].fax, "+31.205060038")
        eq_(self.record.registrant_contacts[0].email, "domains@reasonnet.com")
        eq_(self.record.registrant_contacts[0].created_on, None)
        eq_(self.record.registrant_contacts[0].updated_on, None)

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "P-OEG220")
        eq_(self.record.technical_contacts[0].name, "Olaf Geurs")
        eq_(self.record.technical_contacts[0].organization, "ION")
        eq_(self.record.technical_contacts[0].address, "Vlierweg 12")
        eq_(self.record.technical_contacts[0].city, "Amsterdam")
        eq_(self.record.technical_contacts[0].zip, "1032 LG")
        eq_(self.record.technical_contacts[0].state, "NH")
        eq_(self.record.technical_contacts[0].country, None)
        eq_(self.record.technical_contacts[0].country_code, "NL")
        eq_(self.record.technical_contacts[0].phone, "+31.204949100")
        eq_(self.record.technical_contacts[0].fax, None)
        eq_(self.record.technical_contacts[0].email, "domains@reasonnet.com")
        eq_(self.record.technical_contacts[0].created_on, None)
        eq_(self.record.technical_contacts[0].updated_on, None)

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2014-02-04 08:34:14 UTC'))

    def test_domain_id(self):
        eq_(self.record.domain_id, "334322677_DOMAIN_COM-VRSN")

    def test_expires_on(self):
        assert_raises(yawhois.exceptions.AttributeNotSupported, self.record.expires_on)
