
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.domainregistry.ie/property_contacts_multiple
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisDomainregistryIePropertyContactsMultiple(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.domainregistry.ie/property_contacts_multiple.txt"
        host         = "whois.domainregistry.ie"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 2)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, "JL241-IEDR")
        eq_(self.record.admin_contacts[0].name, "Jonathan Lundberg")
        eq_(self.record.admin_contacts[1].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[1].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[1].id, "JM474-IEDR")
        eq_(self.record.admin_contacts[1].name, "John Moylan")

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "JM474-IEDR")
        eq_(self.record.technical_contacts[0].name, "John Moylan")
