
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.nic.asia/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNicAsiaStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.nic.asia/status_registered.txt"
        host         = "whois.nic.asia"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, ["OK"])

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "cj7.asia")

    def test_reserved(self):
        eq_(self.record.reserved, False)

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 6)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "ns1.dnspod.net")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "ns2.dnspod.net")
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "ns3.dnspod.net")
        eq_(self.record.nameservers[3].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[3].name, "ns4.dnspod.net")
        eq_(self.record.nameservers[4].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[4].name, "ns5.dnspod.net")
        eq_(self.record.nameservers[5].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[5].name, "ns6.dnspod.net")

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, "FR-132aa7afe0967")
        eq_(self.record.admin_contacts[0].name, "Eddie Yeung")
        eq_(self.record.admin_contacts[0].organization, "RAXCO ASSETS CORP.")
        eq_(self.record.admin_contacts[0].address, "RM 1201-1204 12/F\nSEA BIRD HSE\n22-28 WYNDHAM ST CENTRAL HK")
        eq_(self.record.admin_contacts[0].city, "Hong Kong")
        eq_(self.record.admin_contacts[0].zip, "")
        eq_(self.record.admin_contacts[0].state, "")
        eq_(self.record.admin_contacts[0].country_code, "HK")
        eq_(self.record.admin_contacts[0].phone, "+852.21190333")
        eq_(self.record.admin_contacts[0].fax, "")
        eq_(self.record.admin_contacts[0].email, "eddie.yeung@bingogroup.com.hk")

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('2008-01-15 11:28:02 UTC'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, "800046")
        eq_(self.record.registrar.name, "dotASIA R4-ASIA")
        eq_(self.record.registrar.organization, None)
        eq_(self.record.registrar.url, None)

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, "FR-132aa75b4bf65")
        eq_(self.record.registrant_contacts[0].name, "RAXCO ASSETS CORP.")
        eq_(self.record.registrant_contacts[0].organization, "RAXCO ASSETS CORP.")
        eq_(self.record.registrant_contacts[0].address, "RM 1201-1204 12/F\nSEA BIRD HSE\n22-28 WYNDHAM ST CENTRAL HK")
        eq_(self.record.registrant_contacts[0].city, "Hong Kong")
        eq_(self.record.registrant_contacts[0].zip, "")
        eq_(self.record.registrant_contacts[0].state, "")
        eq_(self.record.registrant_contacts[0].country_code, "HK")
        eq_(self.record.registrant_contacts[0].phone, "+852.21190333")
        eq_(self.record.registrant_contacts[0].fax, "+852.23045326")
        eq_(self.record.registrant_contacts[0].email, "eddie.yeung@bingogroup.com.hk")

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "FR-132aa7afe0967")
        eq_(self.record.technical_contacts[0].name, "Eddie Yeung")
        eq_(self.record.technical_contacts[0].organization, "RAXCO ASSETS CORP.")
        eq_(self.record.technical_contacts[0].address, "RM 1201-1204 12/F\nSEA BIRD HSE\n22-28 WYNDHAM ST CENTRAL HK")
        eq_(self.record.technical_contacts[0].city, "Hong Kong")
        eq_(self.record.technical_contacts[0].zip, "")
        eq_(self.record.technical_contacts[0].state, "")
        eq_(self.record.technical_contacts[0].country_code, "HK")
        eq_(self.record.technical_contacts[0].phone, "+852.21190333")
        eq_(self.record.technical_contacts[0].fax, "")
        eq_(self.record.technical_contacts[0].email, "eddie.yeung@bingogroup.com.hk")

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2014-01-15 22:20:16 UTC'))

    def test_domain_id(self):
        eq_(self.record.domain_id, "D93126-ASIA")

    def test_expires_on(self):
        eq_(self.record.expires_on.__class__.__name__, 'datetime')
        eq_(self.record.expires_on, time_parse('2015-01-15 11:28:02 UTC'))

    def test_disclaimer(self):
        eq_(self.record.disclaimer, "DotAsia WHOIS LEGAL STATEMENT AND TERMS & CONDITIONS: The WHOIS service offered by DotAsia and the access to the records in the DotAsia WHOIS database are provided for information purposes only. It allows persons to check whether a specific domain name is still available or not and to obtain information related to the registration records of existing domain names. DotAsia cannot, under any circumstances, be held liable in case the stored information would prove to be wrong, incomplete, or not accurate in any sense.  By submitting a query you agree not to use the information made available to: allow, enable or otherwise support the transmission of unsolicited, commercial advertising or other solicitations whether via email or otherwise; target advertising in any possible way; or to cause nuisance in any possible way to the registrants by sending (whether by automated, electronic processes capable of enabling high volumes or other possible means) messages to them.  Without prejudice to the above, it is explicitly forbidden to extract, copy and/or use or re-utilise in any form and by any means (electronically or not) the whole or a quantitatively or qualitatively substantial part of the contents of the WHOIS database without prior and explicit permission by DotAsia, nor in any attempt hereof, or to apply automated, electronic processes to DotAsia (or its systems). You agree that any reproduction and/or transmission of data for commercial purposes will always be considered as the extraction of a substantial part of the content of the WHOIS database. By submitting the query you agree to abide by this policy and accept that DotAsia can take measures to limit the use of its WHOIS services in order to protect the privacy of its registrants or the integrity of the database.")
