
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.wildwestdomains.com/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisWildwestdomainsComStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.wildwestdomains.com/status_registered.txt"
        host         = "whois.wildwestdomains.com"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, 'registered')

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "wildwestdomains.com")

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 3)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "cns1.secureserver.net")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "cns2.secureserver.net")
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "cns3.secureserver.net")

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, None)
        eq_(self.record.admin_contacts[0].name, "Wild West Domains Wild West Domains")
        eq_(self.record.admin_contacts[0].organization, "Wild West Domains")
        eq_(self.record.admin_contacts[0].address, "14455 N Hayden Rd Suite 219")
        eq_(self.record.admin_contacts[0].city, "Scottsdale")
        eq_(self.record.admin_contacts[0].zip, "85260")
        eq_(self.record.admin_contacts[0].state, "Arizona")
        eq_(self.record.admin_contacts[0].country, None)
        eq_(self.record.admin_contacts[0].country_code, "United States")
        eq_(self.record.admin_contacts[0].phone, "+1.4805058800")
        eq_(self.record.admin_contacts[0].fax, "+1.4805058844")
        eq_(self.record.admin_contacts[0].email, "dns@wildwestdomains.com")
        eq_(self.record.admin_contacts[0].created_on, None)
        eq_(self.record.admin_contacts[0].updated_on, None)

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('2000-08-22 18:29:11'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, None)
        eq_(self.record.registrar.name, "Wild West Domains, LLC")
        eq_(self.record.registrar.organization, "Wild West Domains, LLC")
        eq_(self.record.registrar.url, "http://www.wildwestdomains.com")

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, None)
        eq_(self.record.registrant_contacts[0].name, "Wild West Domains Wild West Domains")
        eq_(self.record.registrant_contacts[0].organization, "Wild West Domains")
        eq_(self.record.registrant_contacts[0].address, "14455 N Hayden Rd Suite 219")
        eq_(self.record.registrant_contacts[0].city, "Scottsdale")
        eq_(self.record.registrant_contacts[0].zip, "85260")
        eq_(self.record.registrant_contacts[0].state, "Arizona")
        eq_(self.record.registrant_contacts[0].country, None)
        eq_(self.record.registrant_contacts[0].country_code, "United States")
        eq_(self.record.registrant_contacts[0].phone, "")
        eq_(self.record.registrant_contacts[0].fax, "")
        eq_(self.record.registrant_contacts[0].email, "")
        eq_(self.record.registrant_contacts[0].created_on, None)
        eq_(self.record.registrant_contacts[0].updated_on, None)

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, None)
        eq_(self.record.technical_contacts[0].name, "Wild West Domains Wild West Domains")
        eq_(self.record.technical_contacts[0].organization, "Wild West Domains")
        eq_(self.record.technical_contacts[0].address, "14455 N Hayden Rd Suite 219")
        eq_(self.record.technical_contacts[0].city, "Scottsdale")
        eq_(self.record.technical_contacts[0].zip, "85260")
        eq_(self.record.technical_contacts[0].state, "Arizona")
        eq_(self.record.technical_contacts[0].country, None)
        eq_(self.record.technical_contacts[0].country_code, "United States")
        eq_(self.record.technical_contacts[0].phone, "+1.4805058800")
        eq_(self.record.technical_contacts[0].fax, "+1.4805058844")
        eq_(self.record.technical_contacts[0].email, "dns@wildwestdomains.com")
        eq_(self.record.technical_contacts[0].created_on, None)
        eq_(self.record.technical_contacts[0].updated_on, None)

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2011-11-01 16:31:47'))

    def test_domain_id(self):
        eq_(self.record.domain_id, None)

    def test_expires_on(self):
        eq_(self.record.expires_on.__class__.__name__, 'datetime')
        eq_(self.record.expires_on, time_parse('2021-11-01 06:59:59'))
