
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.audns.net.au/property_status_with_multiple
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisAudnsNetAuPropertyStatusWithMultiple(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.audns.net.au/property_status_with_multiple.txt"
        host         = "whois.audns.net.au"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, ["serverHold (Expired)", "serverUpdateProhibited (Expired)"])
