
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.dotpostregistry.net/status_registered
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisDotpostregistryNetStatusRegistered(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.dotpostregistry.net/status_registered.txt"
        host         = "whois.dotpostregistry.net"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_status(self):
        eq_(self.record.status, ["TRANSFER PROHIBITED"])

    def test_available(self):
        eq_(self.record.available, False)

    def test_domain(self):
        eq_(self.record.domain, "posteitaliane.post")

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 2)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "dns.poste.it")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "dns2.poste.it")

    def test_admin_contacts(self):
        eq_(self.record.admin_contacts.__class__.__name__, 'list')
        eq_(len(self.record.admin_contacts), 1)
        eq_(self.record.admin_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.admin_contacts[0].type, yawhois.record.Contact.TYPE_ADMINISTRATIVE)
        eq_(self.record.admin_contacts[0].id, "UPU_C1002")
        eq_(self.record.admin_contacts[0].name, "Giovanni Brardinoni")
        eq_(self.record.admin_contacts[0].organization, "Poste Italiane")
        eq_(self.record.admin_contacts[0].address, "Viale Europa 175")
        eq_(self.record.admin_contacts[0].city, "Rome")
        eq_(self.record.admin_contacts[0].zip, "00144")
        eq_(self.record.admin_contacts[0].state, "")
        eq_(self.record.admin_contacts[0].country_code, "IT")
        eq_(self.record.admin_contacts[0].phone, "+39.0659583671")
        eq_(self.record.admin_contacts[0].fax, "+39.0698688651")
        eq_(self.record.admin_contacts[0].email, "Giovanni.Brardinoni@Postecom.it")

    def test_registered(self):
        eq_(self.record.registered, True)

    def test_created_on(self):
        eq_(self.record.created_on.__class__.__name__, 'datetime')
        eq_(self.record.created_on, time_parse('2012-09-21 12:03:07 UTC'))

    def test_registrar(self):
        eq_(self.record.registrar.__class__.__name__, 'Registrar')
        eq_(self.record.registrar.id, "R4947-POST")
        eq_(self.record.registrar.name, "Universal Postal Union")
        eq_(self.record.registrar.organization, None)
        eq_(self.record.registrar.url, None)

    def test_registrant_contacts(self):
        eq_(self.record.registrant_contacts.__class__.__name__, 'list')
        eq_(len(self.record.registrant_contacts), 1)
        eq_(self.record.registrant_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.registrant_contacts[0].type, yawhois.record.Contact.TYPE_REGISTRANT)
        eq_(self.record.registrant_contacts[0].id, "ITPI30001")
        eq_(self.record.registrant_contacts[0].name, "Poste Italiane")
        eq_(self.record.registrant_contacts[0].organization, "Poste Italiane")
        eq_(self.record.registrant_contacts[0].address, "Viale Europa 190")
        eq_(self.record.registrant_contacts[0].city, "Rome")
        eq_(self.record.registrant_contacts[0].zip, "00144")
        eq_(self.record.registrant_contacts[0].state, "")
        eq_(self.record.registrant_contacts[0].country_code, "IT")
        eq_(self.record.registrant_contacts[0].phone, "+39.0659581")
        eq_(self.record.registrant_contacts[0].fax, "+39.065942298")
        eq_(self.record.registrant_contacts[0].email, "info@poste.it")

    def test_technical_contacts(self):
        eq_(self.record.technical_contacts.__class__.__name__, 'list')
        eq_(len(self.record.technical_contacts), 1)
        eq_(self.record.technical_contacts[0].__class__.__name__, 'Contact')
        eq_(self.record.technical_contacts[0].type, yawhois.record.Contact.TYPE_TECHNICAL)
        eq_(self.record.technical_contacts[0].id, "UPU_C1001")
        eq_(self.record.technical_contacts[0].name, "Andrea Speranza")
        eq_(self.record.technical_contacts[0].organization, "Poste Italiane")
        eq_(self.record.technical_contacts[0].address, "Viale Europa 175")
        eq_(self.record.technical_contacts[0].city, "Rome")
        eq_(self.record.technical_contacts[0].zip, "00144")
        eq_(self.record.technical_contacts[0].state, "")
        eq_(self.record.technical_contacts[0].country_code, "IT")
        eq_(self.record.technical_contacts[0].phone, "+39.0659583086")
        eq_(self.record.technical_contacts[0].fax, "+39.0659582032")
        eq_(self.record.technical_contacts[0].email, "netsecurity@postecom.it")

    def test_updated_on(self):
        eq_(self.record.updated_on.__class__.__name__, 'datetime')
        eq_(self.record.updated_on, time_parse('2012-09-21 12:07:40 UTC'))

    def test_domain_id(self):
        eq_(self.record.domain_id, "D19482-POST")

    def test_expires_on(self):
        eq_(self.record.expires_on.__class__.__name__, 'datetime')
        eq_(self.record.expires_on, time_parse('2014-09-21 12:03:07 UTC'))

    def test_disclaimer(self):
        eq_(self.record.disclaimer, "Access to .POST REGISTRY WHOIS information is provided to assist persons in determining the contents of a domain name registration record in the .POST Registry registry database. The data in this record is provided by .POST Registry for informational purposes only, and .POST Registry does not guarantee its accuracy.  This service is intended only for query-based access. You agree that you will use this data only for lawful purposes and that, under no circumstances will you use this data to: (a) allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the data recipient's own existing customers; or (b) enable high volume, automated, electronic processes that send queries or data to the systems of Registry Operator, a Registrar, or Afilias except as reasonably necessary to register domain names or modify existing registrations. All rights reserved. .POST Registry reserves the right to modify these terms at any time. By submitting this query, you agree to abide by this policy.")
