
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.iis.se/se/property_nameservers_single
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisIisSeSePropertyNameserversSingle(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.iis.se/se/property_nameservers_single.txt"
        host         = "whois.iis.se"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 1)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "freja.nhv.se")
        eq_(self.record.nameservers[0].ipv4, "82.96.40.83")
        eq_(self.record.nameservers[0].ipv6, None)
