
# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   spec/fixtures/responses/whois.nic.fr/fr/property_nameservers_with_ipv4_and_some_ipv6
#
# and regenerate the tests with the following script
#
#   $ scripts/generate_tests.py
#

from nose.tools import *
from dateutil.parser import parse as time_parse
import yawhois

class TestWhoisNicFrFrPropertyNameserversWithIpv4AndSomeIpv6(object):

    def setUp(self):
        fixture_path = "spec/fixtures/responses/whois.nic.fr/fr/property_nameservers_with_ipv4_and_some_ipv6.txt"
        host         = "whois.nic.fr"
        part         = yawhois.record.Part(open(fixture_path, "r").read(), host)
        self.record  = yawhois.record.Record(None, [part])

    def test_nameservers(self):
        eq_(self.record.nameservers.__class__.__name__, 'list')
        eq_(len(self.record.nameservers), 6)
        eq_(self.record.nameservers[0].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[0].name, "ns1.nic.fr")
        eq_(self.record.nameservers[0].ipv4, "192.134.4.1")
        eq_(self.record.nameservers[0].ipv6, "2001:660:3003:2::4:1")
        eq_(self.record.nameservers[1].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[1].name, "ns2.nic.fr")
        eq_(self.record.nameservers[1].ipv4, "192.93.0.4")
        eq_(self.record.nameservers[1].ipv6, "2001:660:3005:1::1:2")
        eq_(self.record.nameservers[2].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[2].name, "ns3.nic.fr")
        eq_(self.record.nameservers[2].ipv4, "192.134.0.49")
        eq_(self.record.nameservers[2].ipv6, "2001:660:3006:1::1:1")
        eq_(self.record.nameservers[3].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[3].name, "ns1.ext.nic.fr")
        eq_(self.record.nameservers[3].ipv4, "193.51.208.13")
        eq_(self.record.nameservers[3].ipv6, None)
        eq_(self.record.nameservers[4].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[4].name, "ns4.ext.nic.fr")
        eq_(self.record.nameservers[4].ipv4, "193.0.9.4")
        eq_(self.record.nameservers[4].ipv6, "2001:67c:e0::4")
        eq_(self.record.nameservers[5].__class__.__name__, 'Nameserver')
        eq_(self.record.nameservers[5].name, "ns5.ext.nic.fr")
        eq_(self.record.nameservers[5].ipv4, "206.167.244.5")
        eq_(self.record.nameservers[5].ipv6, None)
